name: .NET Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    working-directory: ./src

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --configuration Release --no-build

    - name: Publish (L)
      run: dotnet publish --configuration Release -r linux-x64 -p:PublishSingleFile=true --self-contained true -o dist_linux

    - name: Upload (L)
      uses: actions/upload-artifact@v4
      with:
        name: Linux executable
        path: src/dist_linux

    - name: Publish (W)
      run: dotnet publish --configuration Release -r win-x64   -p:PublishSingleFile=true --self-contained true -o dist_win
  
    - name: Upload (W)
      uses: actions/upload-artifact@v4
      with:
        name: Windows executable
        path: src/dist_win

    - name: Publish (M)
      run: dotnet publish --configuration Release -r osx-x64   -p:PublishSingleFile=true --self-contained true -o dist_mac
    
    - name: Upload (M)
      uses: actions/upload-artifact@v4
      with:
        name: Mac executable
        path: src/dist_mac
